spring:
  datasource:
#   DB ?? ??? ?
    url: jdbc:h2:tcp://localhost/~/allclear
#    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#       show_sql: true
        format_sql: true

#email
  mail:
    host: smtp.gmail.com
    port: 587
    username: allclear0829.company@gmail.com
    password: qyycekkdhlmyxpby
    properties:
      mail:
        smtp:
          auth: true
          ssl: false
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000


logging.level:
  org.hibernate.SQL: debug